(load "1_main.clp")
(load "../maps/big/nmUrbanized/2_initial_map.clp")
(load "3_env.clp")
(load "../maps/big/nmUrbanized/4_actual_map.clp")
(load "5_agent.clp")
(load "6_init_punteggi.clp")
(load "01_time.clp")
(load "02_inform.clp")
(load "03_punteggi.clp")
(load "04_exit.clp")
(load "05_astar.clp")
(load "06_move.clp")
(load "07_finish.clp")
(load "9_new.clp")
(load "8_a_star.clp")
(load "10_post-astar.clp")
(load "11_path_to_finish.clp")
(load "12_path_to_bestexit.clp")
(reset)

